### ISSUE TITLE
Is the setMaxCurrent multiplying by 50mA for PPS correct?

### ISSUE THREAD

**Issue by Patronics** [CentyLab/AP33772-Cpp#5]
Based on my reading of the USB PD spec, the PPS PDO maximum current is indicated in 10mA steps, but as far as I can tell your code is assuming 50mA steps? I might be missing something though. 

I'm working on a getMaxCurrentForVoltage function based on the same logic, which I'll submit a pull request for once it's done and working :)

**Comment by centydev** [comment]
Hi Patrick, 
Check this one out: https://www.usb.org/sites/default/files/D2T2-1%20-%20USB%20Power%20Delivery.pdf slide 15 does mentioned about PPS current.
